version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:18.03.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.1-r1
            pip install -U pip
            pip install docker-compose==1.22.0-rc1
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py

      - deploy:
          name: Push App Docker image
          command: |
            docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PWD
            docker tag dockerapp_dockerapp $DOCKER_HUB_ID/dockerapp:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_HUB_ID/dockerapp:latest
            docker push $DOCKER_HUB_ID/dockerapp:$CIRCLE_SHA1
            docker push $DOCKER_HUB_ID/dockerapp:latest